### ISSUE TITLE
Is this project only for Live2D-based character ? Not for VRoid ?

### ISSUE THREAD

**Issue by Runa-Chin** [veldanava/AiWaifu#1]
Excuse me, I wanna ask for character bridge of this project. I've seen the readme for example, you demonstrate it with VTube Studo where using Java-based Live2D. About that, this project will compatible with VRoid or not ? They using Unity-based 3D character from pixiv. Tell me is compatible or not.

**Comment by veldanava** [comment]
> Excuse me, I wanna ask for character bridge of this project. I've seen the readme for example, you demonstrate it with VTube Studo where using Java-based Live2D. About that, this project will compatible with VRoid or not ? They using Unity-based 3D character from pixiv. Tell me is compatible or not.

Hello
actually there is a reason why I use VTS

pairing between audio and character
as far as I know, only VTS software is capable of pairing audio with character mouth rigs.

so that's why I recommend using VTS, but if you have ideas for using other software, please try it as well as a reference for the further development of this project.

Thank you also for the open issue ^w^
